export type TrainingStep = {
  label: string;
  description: string;
};

export type TrainingDayPlan = {
  day: number;
  title: string;
  focus: string;
  duration: string;
  description: string;
  steps: TrainingStep[];
  adaptation: string;
  safetyNote: string;
};

export const trainingPlan: TrainingDayPlan[] = [
  {
    day: 1,
    title: "Reconhecendo o corpo",
    focus: "Mobilidade leve e consciência corporal",
    duration: "15 a 20 min",
    description: "Um início leve para observar limites, respiração e controle dos movimentos.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves de pescoço, ombros e braços por 3 a 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade cervical, rotação de ombros e alongamento torácico." },
      { label: "Força/controle", description: "Ponte de glúteos e prancha com joelhos, com foco em controle." },
      { label: "Alongamento", description: "Alongamento leve de coluna, quadris e ombros." },
      { label: "Respiração/relaxamento", description: "Respiração calma por 2 minutos para finalizar." },
    ],
    adaptation: "Se sentir desconforto, reduza amplitude, faça mais pausas ou pule o movimento.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 2,
    title: "Respiração e ritmo",
    focus: "Consciência respiratória e movimentos guiados",
    duration: "15 a 20 min",
    description: "Você vai sincronizar respiração com movimento e repetir com calma.",
    steps: [
      { label: "Aquecimento", description: "Respiração diafragmática sentado por 2 minutos e movimentos leves de braços." },
      { label: "Mobilidade", description: "Rotacao de quadril e alongamento de peitoral com apoio." },
      { label: "Força/controle", description: "Agachamento com apoio de cadeira, focando na descida controlada." },
      { label: "Alongamento", description: "Alongamento de posterior de coxa e quadríceps com apoio." },
      { label: "Respiração/relaxamento", description: "Respiração guiada por 2 minutos em posição confortável." },
    ],
    adaptation: "Use apoio sempre que necessário. Menos repetições, mais controle.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 3,
    title: "Controle corporal básico",
    focus: "Estabilidade e alinhamento",
    duration: "15 a 20 min",
    description: "Hoje o foco é manter o corpo alinhado em movimentos simples.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves de coluna e circulação de braços por 3 minutos." },
      { label: "Mobilidade", description: "Mobilidade de tornozelos, joelhos e quadris com apoio." },
      { label: "Força/controle", description: "Prancha com joelhos e ponte de quadril com pausas." },
      { label: "Alongamento", description: "Alongamento de ombros, costas e quadris." },
      { label: "Respiração/relaxamento", description: "Relaxamento progressivo por 2 minutos." },
    ],
    adaptation: "Reduza o tempo de pausa se for cansativo. A prioridade é o alinhamento.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 4,
    title: "Mobilidade articular",
    focus: "Amplitude sem esforço excessivo",
    duration: "15 a 20 min",
    description: "Aumentar amplitude com movimento lento e controlado.",
    steps: [
      { label: "Aquecimento", description: "Circundução de braços e pernas por 3 minutos." },
      { label: "Mobilidade", description: "Mobilidade de ombros, quadris e tornozelos em círculos." },
      { label: "Força/controle", description: "Agachamento parcial com apoio e ponte de glúteos." },
      { label: "Alongamento", description: "Alongamento dinâmico leve de membros superiores e inferiores." },
      { label: "Respiração/relaxamento", description: "Respiração lenta e relaxamento muscular por 2 minutos." },
    ],
    adaptation: "Não force amplitude. O conforto vem com a repetição.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 5,
    title: "Consciência e repetição",
    focus: "Reforço de padrões básicos",
    duration: "15 a 20 min",
    description: "Repetir movimentos simples com atenção à respiração e ao alinhamento.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves de tronco e braços por 3 minutos." },
      { label: "Mobilidade", description: "Rotação de tronco sentado e mobilidade de ombros." },
      { label: "Força/controle", description: "Prancha com joelhos e agachamento com apoio." },
      { label: "Alongamento", description: "Alongamento de peitoral, quadris e posterior de coxa." },
      { label: "Respiração/relaxamento", description: "Relaxamento com foco na respiração por 2 minutos." },
    ],
    adaptation: "Se cansar, pule uma repetição. O importante é manter a qualidade.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 6,
    title: "Mobilidade + força básica",
    focus: "Unir movimento e controle",
    duration: "20 a 25 min",
    description: "Começar a unir mobilidade com exercícios de força mais estruturados.",
    steps: [
      { label: "Aquecimento", description: "Movimentos articulares gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade de ombros, quadris e coluna com maior amplitude." },
      { label: "Força/controle", description: "Agachamento livre ou com apoio, prancha com joelhos e ponte." },
      { label: "Alongamento", description: "Alongamento de membros superiores e inferiores." },
      { label: "Respiração/relaxamento", description: "Respiração guiada por 2 minutos." },
    ],
    adaptation: "Use apoio se precisar. controle > quantidade.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 7,
    title: "Estabilidade de core",
    focus: "Controle do centro do corpo",
    duration: "20 a 25 min",
    description: "Fortalecer o centro do corpo para dar mais segurança aos movimentos.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 3 a 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade torácica e quadril com apoio." },
      { label: "Força/controle", description: "Prancha com joelhos, prancha lateral adaptada e ponte." },
      { label: "Alongamento", description: "Alongamento abdominal e lombar leve." },
      { label: "Respiração/relaxamento", description: "Relaxamento progressivo por 2 minutos." },
    ],
    adaptation: "Faça pausas longas se precisar. Cada repetição com qualidade conta.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 8,
    title: "Força leve com apoio",
    focus: "Ganhar confiança nos movimentos",
    duration: "20 a 25 min",
    description: "Repetir padrões com leve carga corporal e apoio quando necessário.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular de ombros e quadris." },
      { label: "Força/controle", description: "Agachamento com apoio, prancha com joelhos e flexão de cotovelo na parede." },
      { label: "Alongamento", description: "Alongamento de peitoral, costas e membros inferiores." },
      { label: "Respiração/relaxamento", description: "Respiração lenta por 2 minutos." },
    ],
    adaptation: "Apoie-se sempre que necessário. O ritmo é seu.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 9,
    title: "Controle de tronco",
    focus: "Estabilidade e alinhamento geral",
    duration: "20 a 25 min",
    description: "Trabalhar o controle do tronco em diferentes posições.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos de coluna por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade lombar e torácica com rotações leves." },
      { label: "Força/controle", description: "Prancha com joelhos, ponte de glúteos e antígravity leve." },
      { label: "Alongamento", description: "Alongamento de cadeia posterior e ombros." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Reduza tempo de pausa se for cansativo. Priorize o controle.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 10,
    title: "Revisão da semana",
    focus: "Fixar padrões básicos",
    duration: "20 a 25 min",
    description: "Revisar movimentos da semana com mais consciência.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento com apoio, prancha com joelhos e ponte." },
      { label: "Alongamento", description: "Alongamento completo leve." },
      { label: "Respiração/relaxamento", description: "Respiração guiada por 2 minutos." },
    ],
    adaptation: "Se faltar energia, reduza repetições. O que importa é a execução.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 11,
    title: "Controle corporal",
    focus: "Consciência e precisão",
    duration: "20 a 25 min",
    description: "Aumentar a precisão dos movimentos sem pressa.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves de coluna e respiração por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade de ombros, quadris e tornozelos." },
      { label: "Força/controle", description: "Prancha com joelhos, agachamento sem apoio parcial e ponte com variação." },
      { label: "Alongamento", description: "Alongamento de cadeia posterior e frontal." },
      { label: "Respiração/relaxamento", description: "Respiração por 2 minutos." },
    ],
    adaptation: "Pare quando o corpo pedir. Não corrija tudo de uma vez.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 12,
    title: "Transição e equilíbrio",
    focus: "Estabilidade em apoios reduzidos",
    duration: "20 a 25 min",
    description: "Introduzir pequenos desafios de equilíbrio com segurança.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em tornozelos e quadris." },
      { label: "Força/controle", description: "Agachamento sem apoio, prancha com joelhos e equilíbrio com apoio." },
      { label: "Alongamento", description: "Alongamento de membros superiores e inferiores." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Mantenha o apoio se o equilíbrio for limitado.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 13,
    title: "Controle de ritmo",
    focus: "Execução lenta e consciente",
    duration: "20 a 25 min",
    description: "Diminuir a velocidade dos movimentos para ganhar controle.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em quadris e ombros." },
      { label: "Força/controle", description: "Agachamento lento, prancha com joelhos e ponte controlada." },
      { label: "Alongamento", description: "Alongamento de peitoral, costas e quadris." },
      { label: "Respiração/relaxamento", description: "Respiração guiada por 2 minutos." },
    ],
    adaptation: "Faça menos repetições, mas com mais controle.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 14,
    title: "Integração básica",
    focus: "Unir mobilidade, força e respiração",
    duration: "20 a 25 min",
    description: "Conectar os blocos do treino em uma sequência mais fluida.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves e respiração por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade de ombros, quadris e coluna." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos e ponte em sequência." },
      { label: "Alongamento", description: "Alongamento leve com foco em recuperação." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Se perder o ritmo, pare e recomece devagar.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 15,
    title: "Revisão da jornada",
    focus: "Avaliar evolução até aqui",
    duration: "20 a 25 min",
    description: "Revisar os movimentos e observar como o corpo respondeu.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos e ponte." },
      { label: "Alongamento", description: "Alongamento completo leve." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Ajuste o que for necessário. Hoje é dia de observar, não de exigir.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 16,
    title: "Força funcional leve",
    focus: "Transferir controle para o dia a dia",
    duration: "25 a 30 min",
    description: "Movimentos que aproximam o treino de atividades comuns.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa com foco em quadris." },
      { label: "Força/controle", description: "Agachamento mais baixo, prancha com joelhos e equilíbrio unipodal com apoio." },
      { label: "Alongamento", description: "Alongamento de membros inferiores e superiores." },
      { label: "Respiração/relaxamento", description: "Respiração guiada por 2 minutos." },
    ],
    adaptation: "Mantenha o apoio no equilíbrio se necessário.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 17,
    title: "Controle e precisão",
    focus: "Qualidade do movimento",
    duration: "25 a 30 min",
    description: "Aumentar a precisão sem pressa, valorizando cada repetição.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em coluna e ombros." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos e ponte com controle." },
      { label: "Alongamento", description: "Alongamento com foco em recuperação." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Menos repetições, mais qualidade. O corpo agradece.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 18,
    title: "Estabilidade dinâmica",
    focus: "Controle em movimento",
    duration: "25 a 30 min",
    description: "Introduzir pequenos deslocamentos com controle.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em tornozelos e quadris." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos e transição de apoio para livre." },
      { label: "Alongamento", description: "Alongamento de membros superiores e inferiores." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Use apoio quando precisar. O movimento controlado é o objetivo.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 19,
    title: "Força moderada",
    focus: "Aumentar desafio gradualmente",
    duration: "25 a 30 min",
    description: "Aumentar o desafio de forma segura e progressiva.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento mais profundo, prancha com joelhos e ponte com variação." },
      { label: "Alongamento", description: "Alongamento completo leve." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Se o movimento ficar difícil, reduza amplitude ou faça pausa.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 20,
    title: "Consolidação da força",
    focus: "Reforçar padrões aprendidos",
    duration: "25 a 30 min",
    description: "Revisar e fixar os movimentos da semana.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos e ponte com controle." },
      { label: "Alongamento", description: "Alongamento completo." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Hoje é dia de repetir o que já aprendeu. Qualidade > quantidade.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 21,
    title: "Integração de movimentos",
    focus: "Fluidez entre blocos",
    duration: "25 a 30 min",
    description: "Conectar mobilidade, força e respiração em uma sequência.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves e respiração por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Sequência: agachamento, prancha com joelhos, ponte e equilíbrio." },
      { label: "Alongamento", description: "Alongamento pós-treino completo." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Se perder a fluidez, pare e recomece devagar.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 22,
    title: "Controle avançado",
    focus: "Desafios leves de estabilidade",
    duration: "25 a 30 min",
    description: "Aumentar desafios de estabilidade com segurança.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em quadris e ombros." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos e equilíbrio unipodal com apoio." },
      { label: "Alongamento", description: "Alongamento de membros inferiores e superiores." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Mantenha o apoio no equilíbrio se for instável.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 23,
    title: "Força e consciência",
    focus: "Unir esforço e precisão",
    duration: "25 a 30 min",
    description: "Manter a consciência corporal mesmo com esforço maior.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos, ponte e equilíbrio." },
      { label: "Alongamento", description: "Alongamento completo leve." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Se cansar, faça pausas longas. O controle vem primeiro.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 24,
    title: "Transições controladas",
    focus: "Passar de um movimento para outro",
    duration: "25 a 30 min",
    description: "Praticar transições suaves entre exercícios.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em tronco." },
      { label: "Força/controle", description: "Agachamento para prancha, ponte e mobilidade ativa." },
      { label: "Alongamento", description: "Alongamento pós-treino." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Transições devagar. Não precisa ser rápido.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 25,
    title: "Revisão da semana",
    focus: "Fixar integração dos movimentos",
    duration: "25 a 30 min",
    description: "Revisar e ajustar os movimentos da semana.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos, ponte e equilíbrio." },
      { label: "Alongamento", description: "Alongamento completo." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Observe o que mudou desde o início. Não precisa ser perfeito.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 26,
    title: "Consolidação leve",
    focus: "Juntar tudo com leveza",
    duration: "25 a 30 min",
    description: "Fazer uma sequência mais fluida com o que aprendeu.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Sequência: agachamento, prancha com joelhos, ponte e respiração." },
      { label: "Alongamento", description: "Alongamento completo leve." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Se faltar energia, faça menos repetições. O ritmo é seu.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 27,
    title: "Controle final",
    focus: "Execução com confiança",
    duration: "25 a 30 min",
    description: "Executar movimentos com mais confiança e menos tensão.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular com foco em quadris e ombros." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos, ponte e equilíbrio." },
      { label: "Alongamento", description: "Alongamento pós-treino completo." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Solte a tensão desnecessária. Menos esforço, mais eficiência.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 28,
    title: "Preparação para a conclusão",
    focus: "Revisão final",
    duration: "25 a 30 min",
    description: "Revisar a jornada e observar a evolução do seu corpo.",
    steps: [
      { label: "Aquecimento", description: "Movimentos gerais por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos, ponte e equilíbrio." },
      { label: "Alongamento", description: "Alongamento completo." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Hoje é dia de observar seu progresso. Apenas execute.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 29,
    title: "Fluidez e confiança",
    focus: "Movimento natural",
    duration: "25 a 30 min",
    description: "Deixar o movimento fluir com mais naturalidade.",
    steps: [
      { label: "Aquecimento", description: "Respiração e movimentos leves por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa." },
      { label: "Força/controle", description: "Sequência fluida: agachamento, prancha, ponte e equilíbrio." },
      { label: "Alongamento", description: "Alongamento pós-treino completo." },
      { label: "Respiração/relaxamento", description: "Relaxamento por 2 minutos." },
    ],
    adaptation: "Se algo doer, diminua o ritmo. O conforto é prioridade.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
  {
    day: 30,
    title: "Conclusão da jornada",
    focus: "Celebrar e avaliar",
    duration: "25 a 30 min",
    description: "Fechar a jornada com um treino leve e reflexão sobre a evolução.",
    steps: [
      { label: "Aquecimento", description: "Movimentos leves e respiração por 5 minutos." },
      { label: "Mobilidade", description: "Mobilidade articular completa e leve." },
      { label: "Força/controle", description: "Agachamento, prancha com joelhos, ponte e equilíbrio com calma." },
      { label: "Alongamento", description: "Alongamento completo com foco em prazer." },
      { label: "Respiração/relaxamento", description: "Relaxamento final e reflexão da jornada." },
    ],
    adaptation: "Hoje é dia de comemorar o processo. Faça no seu ritmo.",
    safetyNote: "Pare em caso de dor forte, tontura, formigamento ou desconforto intenso.",
  },
];

export function getTrainingDayPlan(day: number): TrainingDayPlan | undefined {
  return trainingPlan.find((item) => item.day === day);
}
